apiVersion: v1
kind: Service
metadata:
  name: {{ include "talero.fullname" . }}
  labels: {{- include "talero.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 8787
      protocol: TCP
  selector:
    app.kubernetes.io/name: {{ include "talero.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
